name: gis
channels:
- anaconda
- conda-forge
dependencies:
- python=3.6 # try 3.6 matplotlib and rasterio only work together in python 3.5
- matplotlib
- rasterio
- numpy
- shapely
- fiona
- geopandas
- pandas
- pycrs
- xlrd
- ipdb
- keras
- seaborn
- scikit-learn
#- pip:
 #must be installed with conda, conda install -c conda-forge rasterio
